### ISSUE TITLE
klist: No credentials cache found (ticket cache FILE:/tmp/krb5cc_0)

### ISSUE THREAD

**Issue by andreypz** [cern-eos/eos#19]
Hi,

I'm on SLC6 AFS machine.
When I do `sudo eosfusebind`, I get an error:

> klist: No credentials cache found (ticket cache FILE:/tmp/krb5cc_0)
could not find automatically a credential file

I think it's coming from eos.
My ticket cache file in fact exists at `/tmp/krb5cc_13052_D6hsrG`

**Comment by mvala** [comment]
Just do as normal user
```
eosfusebind
```

**Comment by mvala** [comment]
It works for me
```
[mvala@lxplus002 ~]$ kdestroy 
kdestroy: No credentials cache found while destroying cache
[mvala@lxplus002 ~]$ kinit 
Password for mvala@CERN.CH: 
[mvala@lxplus002 ~]$ eosfusebind 
[mvala@lxplus002 ~]$ ls -al /eos/user/m/mvala
total 809K
drwx------. 1 mvala  z2    35G Feb  7 21:57 .
drwxr-xr-x. 1 daemon root  66T Jun 22 08:57 ..
drwx------. 1 mvala  z2   1.8G Jun 19 10:24 Documents
drwx------. 1 mvala  z2   1.2G Jan 12 20:21 eBooks
-rw-r--r--. 1 mvala  z2   405K Mar 18  2016 hsimple.root
drwx------. 1 mvala  z2    27G Apr 18 09:05 Photos
drwx------. 1 mvala  z2    53M Nov 13  2017 tmp
drwx------. 1 mvala  z2    17M Mar 21  2017 tmva
drwx------. 1 mvala  z2   4.4G Dec 15  2017 Videos
[mvala@lxplus002 ~]$ cat /eos/user/proc/whoami
Virtual Identity: uid=21495 (21495,99) gid=1395 (1395,99) [authz:krb5] host=lxplus002.cern.ch domain=cern.ch
[mvala@lxplus002 ~]$ id
uid=21495(mvala) gid=1395(z2) groups=1395(z2),1092772198 context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```
What does it mean "SLC6 AFS machine"?

**Comment by andreypz** [comment]
On lxplus I don't have problems either (in fact, I don't need to run fusebind, it's mounted automatically).

> What does it mean "SLC6 AFS machine"?
It is a non-lxplus machine at CERN, with SLC6 installed via http://linux.web.cern.ch/linux/install/

**Comment by mvala** [comment]
I see and did you configure eos fuse? can you show me files? `/etc/sysconfig/eos.user and /etc/auto.eos?

**Comment by franck-eyraud** [comment]
> >  klist: No credentials cache found (ticket cache FILE:/tmp/krb5cc_0)
> >   could not find automatically a credential file
>
> I think it's coming from eos.
> My ticket cache file in fact exists at /tmp/krb5cc_13052_D6hsrG

Hi Andrey,

I seems that `eosfusebind` is not looking for the correct ticket cache. It's trying to read `krb5cc_0` which is usually the ticket cache for root. 
`eosfusebind` (as do `klist` and `kinit`) tries to access the ticket cache pointed out by the KRB5CCNAME environment variable. It is set to root ticket cache usually when running `su <user>`, this keeps the environment from root session. 
To use a fresh environment, you need to run `su - <user>`. Or just manually set the variable to the know ticket cache : `export KRB5CCNAME=file:/tmp/krb5cc_13052_D6hsrG`

**Comment by andreypz** [comment]
Hi @mvala 
My `/etc/sysconfig/eos.user` is:
> export EOS_FUSE_MGM_ALIAS=eoscms.cern.ch
> export EOS_FUSE_MOUNTDIR=/eos/cms
> export EOS_FUSE_USER_KRB5CC=1

The `/etc/auto.eos` did not exist. I copied the file from lxplus machine, but it did not help.

@franck-eyraud : as I learned from @mvala the sudo is not necessary to run eosfusebind. So that is not the issue. When I run without sudo, there is no error. But simply the eos is not mounted.

So, the question here really is: how to mount eos on non-lxplus SLC6 machines. Do you have instructions for that?

**Comment by franck-eyraud** [comment]
I'm not a cern user, and we use EL7, but the procedure to mount a eos folder providing the file `/etc/sysconfig/eos.user` is correct and you have root access should be `service eosd start user`.
Otherwise, you should also be able to create a user mount with command `eos fuse mount /home/user/mount-dir`, but I think this is not what you want to do.

**Comment by andreypz** [comment]
Closing this issue.
It's not realy related to kinit. Just mounting configs of eos.
I managed to make it work now, following instructions [here](https://cern.service-now.com/service-portal/article.do?n=KB0003846) and [here](http://eos-docs.web.cern.ch/eos-docs/configuration/fuse.html#eosd-shared-mount)
