### ISSUE TITLE
Missing dependency for killall on el7

### ISSUE THREAD

**Issue by franck-eyraud** [cern-eos/eos#2]
Cannot stop (and neither restart) the eossync service on el7, although the command returns `[OK]`.

The `killall` command is not installed by default any more, and is contained in the `psmisc` package.

**Comment by esindril** [comment]
Fixed by this commit:
https://gitlab.cern.ch/dss/eos/commit/25c906e256835f94d55cfb7bb235d8afc91be43f

**Comment by franck-eyraud** [comment]
Hi Elvin, just to notify that it seems it didn't come into aquamarine branch, so we needed to install psmisc manually on our new servers ;)
