### ISSUE TITLE
example of a simple project that uses eos client  

### ISSUE THREAD

**Issue by vkhristenko** [cern-eos/eos#20]
Hello!

Is there any documentation regarding how to compile a simple project that would use 
an eos client. Suppose I have and do the following:

- I do have x509 and kerberos permissions to access various eos instances (like eoscms, etc.). Let's say i'm on lxplus and all i want is programmatically access files on eos...
- I would like to test my application reading some file, i know that there are higher level apis (from root, this is not the point in here)
- I use c and would like to get access to headers and shared object files that would allow me to compile and use the c eos client

I apologize for asking if this already exists, but from your repo that is not quite clear

Thanks!

**Comment by vkhristenko** [comment]
Hi,

any chance to have any response on this ?

_just to reiterate, i want to be able to write a simple app to read from eos storage. let's say i have a custom binary file_

thanks a lot!

VK

**Comment by esindril** [comment]
Hi Viktor,

You only need to use the xrootd-client to interact with EOS. The handling of authentication be it Kerberos or GSI certificates is done by the xrootd client. Through the XrdCl::File and XrdCl::FileSystem interfaces form xrootd you can read/write and query for different information directly EOS.

Hope this helps.
Cheers,
Elvin

**Comment by esindril** [comment]
Btw, there is no specific eos-client, it all uses the xrootd-client underneath, even the eos console uses that.

Elvin

**Comment by vkhristenko** [comment]
Hi Elvin,

ok! thanks a lot! I  just thought that you already had some kind of hello world to get started from.

i will take a look at the console in that case! 

__thanks!!!__

VK

**Comment by esindril** [comment]
Here you have examples on how to use the XrdCl::File interface to read/write. You just have to set the proper URL to point to the instance you like. There are more examples in the same directory:
https://github.com/xrootd/xrootd/blob/master/tests/XrdClTests/FileTest.cc

**Comment by vkhristenko** [comment]
__thanks a lot once again!!!__
