### ISSUE TITLE
eos fs config logicalpath

### ISSUE THREAD

**Issue by mhpopescu** [cern-eos/eos#22]
Eos version used: EOS 4.4.23 (CERN)

Configuration page[1] states about logical path that it can be used like this:
> To activate the logical path setting,
 the following command must be executed:
> ```bash
>   eos fs config <fsid> logicalpath=1
>``` 

Considering that i have a fs with `fsid=1`, that command result in an error:
```bash
$ eos fs config 1 logicalpath=1
error: not an allowed parameter <logicalpath>
```

In man page for `eos fs config` there is no `logicalpath` as `key`:
```text
fs config <fsid>|<uuid>|<host>:<port> <key>=<value>\
    configure the filesystem parameter, where <key> and <value> can be:   
    configstatus=rw|wo|ro|drain|draindead|off|empty [--comment "<comment>"]
      rw        : set filesystem in read-write mode
      wo        : set filesystem in write-only mode
      ro        : set filesystem in read-only mode
      drain     : set filesystem in drain mode
      draindead : set filesystem in draindead mode, unusable for any read
      off       : disable filesystem
      empty     : empty filesystem, possible only if there are no
                  more files stored on it
      --comment : pass a reason for the status change
    headroom=<size>
      headroom to keep per filesystem. <size> can be (>0)[BMGT]
    scaninterval=<seconds>
      configure a scanner thread to recheck the file & block checksum
      of all stored files every <seconds>. 0 disables scanning
    scanrate=<MB/s>
      configure the maximum scan rate
    graceperiod=<seconds>
      grace period before a filesystem with an operation error gets
      automatically drained
    drainperiod=<seconds>
      period a drain job is allowed to finish the drain procedure
    proxygroup=<proxy_grp_name>
      schedule a proxy for the current filesystem by taking it from
      the given proxy group. The special value "<none>" is the
      same as no value and means no proxy scheduling
    filestickyproxydepth=<depth>
      depth of the subtree to be considered for file-stickyness. A
      negative value means no file-stickyness
    forcegeotag=<geotag>
      set the filesystem's geotag, overriding the host geotag value.
      The special value "<none>" is the same as no value and means
      no override
    s3credentials=<accesskey>:<secretkey>
      the access and secret key pair used to authenticate
      with the S3 storage endpoint
```

[1] https://github.com/cern-eos/eos/blob/master/doc/configuration/logicalpath.rst

**Comment by mpatrascoiu** [comment]
Hello,

The logicalpath setting is a feature developed as part of a larger project called XDC.
However, these changes are not yet merged into the EOS main branch. 
(Hence why the `fs config` command won't show the `logicalpath` key)

If interested, you can download the `xdc` version from the following repo: http://storage-ci.web.cern.ch/storage-ci/eos/citrine-xdc/commit/el-7/ (compiled from the last `xdc` branch commit, based on 4.4.18 tag)

It's true that they do appear in the documentation.
We generate the docs website automatically from git versioned RST files: https://eos-docs.web.cern.ch/eos-docs/

For XDC changes, it was desirable to keep them documented in the same place as all other EOS features. However, as not part of the main branch, links pointing to these pages have been hidden on the website.

I hope this clears out any issues.

**Comment by mhpopescu** [comment]
This makes sense. Thank you.
