### ISSUE TITLE
Build error with zeromq 4.2.1

### ISSUE THREAD

**Issue by ThiefMaster** [cern-eos/eos#9]
I just tried building EOS on my Gentoo system with zeromq-4.2.1 and got the following error:

```
In file included from /home/adrian/eos/eos/common/ZMQ.hh:37:0,
                 from /home/adrian/eos/eos/common/ZMQ.cc:25:
/home/adrian/eos/eos/utils/zmq.hpp: In member function ‘void zmq::socket_t::monitor(zmq::monitor_t*)’:
/home/adrian/eos/eos/utils/zmq.hpp:407:6: error: ‘zmq_event_t’ was not declared in this scope
      zmq_event_t event;
      ^
/home/adrian/eos/eos/utils/zmq.hpp:423:16: error: ‘event’ was not declared in this scope
       memcpy (&event, zmq_msg_data (&msg), sizeof (event));
                ^
make[2]: *** [common/CMakeFiles/eosCommonServer.dir/build.make:183: common/CMakeFiles/eosCommonServer.dir/ZMQ.cc.o] Error 1
```

After downgrading to zeromq-3.2.5 it worked fine. Since 4.2.1 is the "stable" version of zeromq on Gentoo it would be nice if both versions were supported.

http://zeromq.org/docs:4-1-upgrade

**Comment by kyrsjo** [comment]
You need to install the newest c++ zeromq-devel packagage for your distro; see 
https://its.cern.ch/jira/browse/EOS-1827?filter=-2

Also, the version of EOS on GitHub is quite outdated...
